name: client
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  formz: ^0.4.1

  flutter_map: ^0.14.0
  location: ^4.2.0

  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.14
  url_launcher: ^6.0.12

  gallery_saver: ^2.3.1
  image_picker: ^0.8.5+3
  cross_file_image: ^0.0.2
  fluttertoast: ^8.0.9

  flutter_focus_watcher: ^2.0.0
  json_annotation: ^4.4.0
  mime: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_status_received.png
    - assets/ic_status_approved.png
    - assets/ic_status_solved.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
