version: "3.9"
services:
  hogweed_server:
    container_name: hogweed_server
    env_file:
      - samples/sample_config.env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        WORKDIR: $DOCKER_VOLUME
    ports:
      - ${PORT}:3000
      - "9229:9229"
    depends_on:
      - postgres
    volumes:
      - docker-volume:/$DOCKER_VOLUME
    networks:
      - hogweednetwork

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - docker-volume:/data/db
    ports:
      - "27018:27017"
    # command: mongod --noauth
    networks:
      - hogweednetwork

networks:
  hogweednetwork:
    driver: bridge

volumes:
    docker-volume:
