# This file exists until [the bug](https://github.com/docker/compose/issues/7964) is fixed, will be replaced by generated after.
networks:
  default:
    driver: bridge
secrets:
  nginx-config:
    file: ./default.conf.template
services:
  hogweed_server:
    container_name: hogweed_server
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - ../config.env
    environment:
      DOCKER: 'True'
      ENV: production
      POSTGRES_PORT: 5432
      HOGWEED_PORT: 3000
      SERVER_PORT: 1337
    expose:
      - 3000
    image: '..'
    restart: always
    volumes:
      - ./docker-volume/backup:/app/backup:rw
      - ./docker-volume/logs:/app/logs:rw
      - ./docker-volume/media:/app/media:rw
      - ./docker-volume/static:/app/static:rw
  nginx_gateway:
    container_name: nginx_gateway
    depends_on:
      hogweed_server:
        condition: service_started
    environment:
      HOGWEED_PORT: 3000
      NGINX_ENVSUBST_TEMPLATE_DIR: /run/secrets
      NGINX_PORT: 8800
    image: nginx
    ports:
      - published: 1337
        target: 8800
    restart: always
    secrets:
      - source: nginx-config
        target: default.conf.template
    volumes:
      - ./docker-volume/media:/app/media:rw
      - ./docker-volume/static:/app/static:rw
  postgres:
    container_name: postgres
    env_file:
      - ./config.env
    expose:
    - 543
    image: postgis/postgis
    restart: always
version: '3.9'
volumes:
  docker-volume: {}
