version: "3.9"

services:
  hogweed_server:
    container_name: hogweed_server
    env_file:
      - ../config.env
    environment:
      - DOCKER=True
      - ENV
      - POSTGRES_PORT=5432
      - HOGWEED_PORT
      - SERVER_PORT
    depends_on:
      - postgres
    expose:
      - $HOGWEED_PORT
    volumes:
      - ../docker-volume/static:/app/static
      - ../docker-volume/media:/app/media
      - ../docker-volume/backup:/app/backup
      - ../docker-volume/logs:/app/logs

  nginx_gateway:
    image: nginx
    container_name: nginx_gateway
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/configs
      - NGINX_PORT
      - HOGWEED_PORT
    depends_on:
      - hogweed_server
    ports:
      - ${SERVER_PORT}:${NGINX_PORT}
    configs:
      - source: nginx-config
        target: /configs/default.conf.template
    volumes:
      - ../docker-volume/static:/app/static
      - ../docker-volume/media:/app/media

  postgres:
    image: postgis/postgis
    restart: always
    container_name: postgres
    env_file:
      - ../config.env
    expose:
      - 5432

configs:
  nginx-config:
    file: ./default.conf.template

secrets:
  ssl-config:
    file: ...

networks:
  default:
    driver: bridge

volumes:
  docker-volume: {}
