version: "3.9"

services:
  hogweed_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - WORKDIR=app
        - HOGWEED_PORT

  nginx_gateway: {}

  mail-agent: {}

  postgres:
    volumes:
      - ../docker-volume/database:/data/db
