# Delete lines 184-186 in settings.py to use!

FROM python:3.10.4-slim as builder
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ARG WORKDIR

WORKDIR ./$WORKDIR
COPY ./Pipfile ./

RUN mkdir ./.venv
RUN pip install pipenv
RUN pipenv install --skip-lock

FROM python:3.10.4-slim as runner
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ARG WORKDIR
ARG HOGWEED_PORT

RUN apt-get update && apt-get install -y binutils libproj-dev gdal-bin net-tools postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR ./$WORKDIR
COPY --from=builder ./$WORKDIR/.venv ./.venv
COPY . .

ENV VIRTUAL_ENV=./.venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE $HOGWEED_PORT

ENTRYPOINT ./docker/docker-entrypoint.sh
