version: "3.9"

services:
  hogweed_server:
    container_name: hogweed_server
    env_file:
      - ../config.env
    environment:
      DOCKER: 'True'
      ENV: $ENV
      POSTGRES_PORT: 5432
      HOGWEED_PORT: $HOGWEED_PORT
      SERVER_PORT: $SERVER_PORT
    depends_on:
      - postgres
    expose:
      - $HOGWEED_PORT
    volumes:
      - ../docker-volume/static:/app/static
      - ../docker-volume/media:/app/media

  nginx_gateway:
    image: nginx
    container_name: nginx_gateway
    environment:
      NGINX_ENVSUBST_TEMPLATE_DIR: /run/secrets
      NGINX_PORT: $NGINX_PORT
      HOGWEED_PORT: $HOGWEED_PORT
    depends_on:
      - hogweed_server
    ports:
      - ${SERVER_PORT}:${NGINX_PORT}
    secrets:
      - source: nginx-config
        target: default.conf.template
    volumes:
      - ../docker-volume/static:/app/static
      - ../docker-volume/media:/app/media

  postgres:
    image: postgis/postgis
    restart: always
    container_name: postgres
    env_file:
      - ../config.env
    expose:
      - 5432

secrets:
  nginx-config:
    file: ./default.conf.template

networks:
  default:
    driver: bridge

volumes:
  docker-volume: {}
